worflow test

diff --git a/.github/workflows/npm-resume.yml b/.github/workflows/npm-resume.yml
--- a/.github/workflows/npm-resume.yml
+++ b/.github/workflows/npm-resume.yml
@@ -45,7 +45,7 @@ jobs:
         run: npm ci
 
       - name: Test
-        run: npm test
+        run: npm test || echo "Tests failed" && exit 1
 
   release:
     needs: test
